# Context
server:
  # Context
  servlet:
    context-path: /system
  # Server
  port: 9191

spring:
  datasource:
    hikari:
      username: root
      password: rootmysql
    url: jdbc:mysql://localhost:3306/system-ktl?autoReconnect=true&useSSL=false
    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        ddl-auto: validate