version: '3.4'
services:

  db:
    image: mariadb:10.2
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=rootmysql
      - MYSQL_DATABASE=system-ktl
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    networks:
      - network-app
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db-volume:/var/lib/mysql

networks:
  network-app:
volumes:
  db-volume: